---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./platform/applications
  prune: true
  dependsOn:
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: domain
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./platform/domain
  prune: true
  dependsOn:
    - name: applications
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: interfaces
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./platform/interfaces
  prune: true
  dependsOn:
    - name: domain
  sourceRef:
    kind: GitRepository
    name: flux-system